# Generated by Django 5.0.3 on 2024-06-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('code', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('PR', 'PROTEIN'), ('VT', 'VITAMINS'), ('CR', 'CREATINE'), ('AA', 'AMINO-ACID'), ('PW', 'PRE-WORKOUT')], max_length=100)),
            ],
        ),
    ]
