# Generated by Django 5.0.3 on 2024-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplementStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
