# Generated by Django 5.0.3 on 2024-06-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplementStoreApp', '0002_alter_supplement_available_alter_supplement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
