# Generated by Django 5.0.3 on 2024-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='brojOdrzaniNastani',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='godinaFormiranje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='ime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='imeDrzava',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='daliENaOtvoreno',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='vremeOdrzuvanje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
