# Generated by Django 5.0.3 on 2024-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
