# Generated by Django 5.0.6 on 2024-05-27 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('adresa', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=50)),
                ('fotografija', models.ImageField(blank=True, null=True, upload_to='hrana/')),
                ('cena', models.IntegerField()),
                ('kolicina', models.IntegerField()),
                ('kategorija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.kategorija')),
                ('kreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prodazba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.klient')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.product')),
            ],
        ),
    ]
